## Beginner to Advanced List Comprehension Practice Problems
##### https://towardsdatascience.com/beginner-to-advanced-list-comprehension-practice-problems-a89604851313

In [4]:
numbers = []
for i in range(1,1001):
   numbers.append(i)
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000]

#### 1. Find all of the numbers from 1–1000 that are divisible by 8

In [8]:
nums = [i for i in range(1,1001) if i %8==0]

In [9]:
nums

[8,
 16,
 24,
 32,
 40,
 48,
 56,
 64,
 72,
 80,
 88,
 96,
 104,
 112,
 120,
 128,
 136,
 144,
 152,
 160,
 168,
 176,
 184,
 192,
 200,
 208,
 216,
 224,
 232,
 240,
 248,
 256,
 264,
 272,
 280,
 288,
 296,
 304,
 312,
 320,
 328,
 336,
 344,
 352,
 360,
 368,
 376,
 384,
 392,
 400,
 408,
 416,
 424,
 432,
 440,
 448,
 456,
 464,
 472,
 480,
 488,
 496,
 504,
 512,
 520,
 528,
 536,
 544,
 552,
 560,
 568,
 576,
 584,
 592,
 600,
 608,
 616,
 624,
 632,
 640,
 648,
 656,
 664,
 672,
 680,
 688,
 696,
 704,
 712,
 720,
 728,
 736,
 744,
 752,
 760,
 768,
 776,
 784,
 792,
 800,
 808,
 816,
 824,
 832,
 840,
 848,
 856,
 864,
 872,
 880,
 888,
 896,
 904,
 912,
 920,
 928,
 936,
 944,
 952,
 960,
 968,
 976,
 984,
 992,
 1000]

#### 2. Find all of the numbers from 1–1000 that have a 6 in them

In [12]:
nums = [i for i in range(1,1001) if '6' in str(i) ]

In [13]:
nums

[6,
 16,
 26,
 36,
 46,
 56,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 76,
 86,
 96,
 106,
 116,
 126,
 136,
 146,
 156,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 176,
 186,
 196,
 206,
 216,
 226,
 236,
 246,
 256,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 276,
 286,
 296,
 306,
 316,
 326,
 336,
 346,
 356,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 376,
 386,
 396,
 406,
 416,
 426,
 436,
 446,
 456,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 476,
 486,
 496,
 506,
 516,
 526,
 536,
 546,
 556,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 576,
 586,
 596,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 706,
 716,
 726,
 736,
 746,
 756,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 776,
 786,
 796,
 806,
 816,
 826,
 836,
 846,
 856,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 876,
 886,
 896,
 906,
 916,
 926,
 936,
 946,
 956,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 976,
 986,
 996]

#### 3. Count the number of spaces in a string

In [14]:
string = "Practice Problems to Drill List Comprehension in Your Head."

In [25]:
n=0
countspace=len([ s for s in string if s == " "])

In [26]:
countspace

8

#### 4. Remove all of the vowels in a string

In [31]:
string = "Practice Problems to Drill List Comprehension in Your Head."

In [3]:

vowels = "".join([ v for v in string if v not in ['a','e','i','o','u'] ])

In [19]:
x = " "
for v in string:
    if v not in ['a','e','i','o','u'] :
        x += v
        
print(str(x))

 Prctc Prblms t Drll Lst Cmprhnsn n Yr Hd.

### 5. Find all of the words in a string that are less than 5 letters

In [23]:
lessthan5 = [x for x in string.split() if len(x) < 5]

In [24]:
lessthan5

['to', 'List', 'in', 'Your']

### 6 Use a dictionary comprehension to count the length of each word in a sentence (use string above)

In [41]:
q6_answer = {word:len(word)for word in string}

In [42]:
q6_answer

{'P': 1,
 'r': 1,
 'a': 1,
 'c': 1,
 't': 1,
 'i': 1,
 'e': 1,
 ' ': 1,
 'o': 1,
 'b': 1,
 'l': 1,
 'm': 1,
 's': 1,
 'D': 1,
 'L': 1,
 'C': 1,
 'p': 1,
 'h': 1,
 'n': 1,
 'Y': 1,
 'u': 1,
 'H': 1,
 'd': 1,
 '.': 1}

In [43]:
lst1=[2, 4, 6, 8, 10, 12, 14]

#Type your answer here.

lst2=[x for x in lst if x**2 > 50]


print(lst2)

NameError: name 'lst' is not defined

In [67]:
dict={"Sedan": 1500, "SUV": 2000, "Pickup": 2500, "Minivan": 1600, "Van": 2400, "Semi": 13600, "Bicycle": 7, "Motorcycle": 110}

#Type your answer here.

lst=[x.upper() for x,y in dict.items() if y < 5000]

print(lst)

['SEDAN', 'SUV', 'PICKUP', 'MINIVAN', 'VAN', 'BICYCLE', 'MOTORCYCLE']

In [63]:
dict1={"Sedan": 1500, "SUV": 2000, "Pickup": 2500, "Minivan": 1600, "Van": 2400, "Semi": 13600, "Bicycle": 7, "Motorcycle": 110}
for x,y in dict1.items():
    if y < 5000:
        print(x.upper())

SEDAN
SUV
PICKUP
MINIVAN
VAN
BICYCLE
MOTORCYCLE